= Charles Fisher Sparrell

Born on October 26, 1928 in Worcester, Massachusetts. Died on September 25, 2007 in Scituate, Massachusetts. Son of link:https://github.com/sparrell/CfsJksAs/blob/main/priv/static/adoc/V2_C5_G1/gen1.P.Herbert_Kirkwood_Sparrell.adoc[Herbert K. Sparrell] and link:https://github.com/sparrell/CfsJksAs/blob/main/priv/static/adoc/V2_C5_G1/gen1.M.Marion_F_Fisher.adoc[Marion Fisher].

Charles F Sparrell was an uncommonly gifted Civil Engineer who specialized in Loss Prevention and Safety Engineering. Upon graduating from Norwich University with the Class of 1949, he leveraged his Bachelor of Science degree in Civil Engineering into a position building bridges for the state of Maine. He transitioned to a role with Liberty Mutual Insurance Company where his strong reputation sustained and advanced his career until his eventual retirement as Assistant Vice President of Loss Prevention. 

Among his many noteworthy professional contributions, Charles F Sparrell helped supervise the construction of the Gateway Arch in St. Louis, Missouri. That project enjoyed an accident rate twenty percent better than expected. So too, Charles F Sparrell was a pioneer in the scientific testing of automobile safety devices now considered industry standard. 

In addition to his storied work life, Charles F Sparrell served honorably in the Army Reserve Corps of Engineers. Upon graduation, he was commissioned a second lieutenant and attached to an armored cavalry unit. In 1958, he was promoted to the rank of captain.