= Albert Fisher

Born in 1812, Albert Fisher was a railroad engineer whose work in Maine potentially connected him with his wife, Arvilla Gray (1808-1888). Since their deaths a year apart in the 1880s, the Fishers have occupied a static role in the family tree, with both Frances Fisher (b. 1835) and Albert AF Fisher (b. 1854) integrated as presumed children of the couple.
That logic has changed recently as emerging evidence suggests that Frances Fisher was the only child of Albert and Arvilla Fisher and that Albert AF Fisher, who was raised as her brother, was, in fact, her son. 
This accounts for the lack of a birth mother and parent birthplace information on Albert AF Fisher’s 1854 birth record as well as the nineteen-year gap between Frances and Albert AF’s births. Biologically, Frances was the more likely mother of Albert AF Fisher. Her mother (and Albert AF’s historically recognized mother), Arvilla Gray Fisher would have been forty-six at the time of young Albert’s birth.
Though not confirmed, the likelihood of this scenario is weighty enough to merit a reconfiguration in the family tree so that Albert Fisher is recognized as Albert AF Fisher’s grandfather and not his father. 
