defmodule Cfsjksas.Annuli.Get do
  @moduledoc """
  routines for constants in for each generation
  """
  @ancestors_svg "static/images/ancestors_annuli.svg"

#  @mxc 21000  # center of page
#  @myc 21000  # center of page
#  @radii %{ 0 => 2000, 1 =>600, 2 =>600, 3 => 1000, 4 => 1000, 5 => 1000, 6 => 1000,
#            7 => 2500, 8 => 2000, 9 => 2400, 10 => 2300, 11 => 1500, 12 => 1200,
#            13 => 1200, 14 => 300, 15 => 50, 16 => 50, -1 => 0 }
#  @outer_ring_radius 20000

  @mxc 10000  # center of page
  @myc 10000  # center of page
  @radii %{ 0 => 300, 1 =>100, 2 =>300, 3 => 300, 4 => 400, 5 => 300, 6 => 300,
            7 => 300, 8 => 500, 9 => 1100, 10 => 1000, 11 => 1000, 12 => 1000,
            13 => 1000, 14 => 900, 15 => 500, 16 => 50, -1 => 0 }
@outer_ring_radius 15000

  @config %{
    0 => %{
      stroke_color: "black",
      stroke_width: "8",
      shape_fill: "none",
      n_font_size: "50",
      d_font_size: "40",
      n_font_family: "Times, serif, bold",
      d_font_family: "Times, serif, cursive",
      text_fill: "black",
      name1: "Charles Fisher Sparrell",
      date1: "(1928 - 2007)",
      name2: "James Kirkwood Sparrell",
      date2: "(1932 - 2015)",
      name3: "Ann Sparrell",
      date3: "(1933 - 2023)",
      delta_y_n1: -115,
      delta_y_d1: -80,
      delta_y_n2: -20,
      delta_y_d2: 20,
      delta_y_n3: 80,
      delta_y_d3: 110,
    },
    1 => %{
      steps: 1,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      step_radius: 0,
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    2 => %{
      steps: 1,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      step_radius: 0,
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    3 => %{
      steps: 1,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      step_radius: 0,
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    4 => %{
      steps: 1,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      step_radius: 0,
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    5 => %{
      steps: 1,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      step_radius: 0,
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    6 => %{
      steps: 1,
      step_radius: 0,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    7 => %{
      steps: 2,
      step_radius: 150,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    8 => %{
      steps: 4,
      step_radius: 200,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    9 => %{
      steps: 4,
      step_radius: 200,
      gn_font_size: "20",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "25",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "15",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 100,
      r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    10 => %{
      steps: 8,
      step_radius: 100,
      gn_font_size: "10",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "10",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "10",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 50,
      r_y: 50,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    11 => %{
      steps: 8,
      step_radius: 100,
      gn_font_size: "10",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "10",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "10",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 50,
      r_y: 50,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    12 => %{
      steps: 8,
      step_radius: 100,
      gn_font_size: "10",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "10",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "10",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 50,
      r_y: 50,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    13 => %{
      steps: 8,
      step_radius: 100,
      gn_font_size: "10",
      gn_font_family: "Times,serif",
      gn_y: -20,
      sn_font_size: "10",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      d_font_size: "10",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      r_x: 50,
      r_y: 50,
      #r_x: 100,
      #r_y: 100,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
    14 => %{
      steps: 2,
      step_radius: 100,
      #gn_font_size: "20",
      gn_font_size: "10",
      gn_font_family: "Times,serif",
      gn_y: -20,
      #sn_font_size: "25",
      sn_font_size: "10",
      sn_font_family: "Times,serif,bold",
      sn_y: 0,
      #d_font_size: "15",
      d_font_size: "10",
      d_font_family: "Times,serif,cursive",
      d_y: 20,
      text_fill: "black",
      #r_x: 100,
      #r_y: 100,
      r_x: 50,
      r_y: 50,
      fill_opacity: "60%",
      stroke: "none",
      stroke_width: "0",
      line_stroke: "lightgray",
      line_stroke_width: "1",
    },
  }

  def path(:ancestors_svg) do
    Path.join(:code.priv_dir(:cfsjksas), @ancestors_svg)
  end

  def config(gen) do
    @config[gen]
  end

  def center() do
    {@mxc, @myc}
  end

  def viewbox() do
    {2 * @mxc, 2 * @myc}
  end

  def radius(:outer_ring) do
    @outer_ring_radius
  end
  def radius(-1) do
    @radii[-1]
  end
  def radius(0) do
    @radii[0]
  end
  def radius(n) do
    @radii[n] + radius(n-1)
  end

  def xy(radius, radians) do
    x = @mxc + ( Complex.from_polar(radius, radians) |> Complex.real() |> round() )
    # recall y is positive is down not up in svg
    y = @myc - ( Complex.from_polar(radius, radians) |> Complex.imag() |> round() )
    {x,y}
  end


end
