= Humphrey Atherton (1607 - 1661)

Narrative TBD


== Vital Stats


* Sex: M
* Birth: ABT 1607
* Birthplace: Minwick, Lancashire, England, UK
* Death: 17 SEP 1661
* Deathplace: Dorchester, Boston, Suffolk, Massachusetts, USA
* Age at Death: About 53-54


== Family
* Mother: Out of Scope

* Father: Out of Scope

* Child*: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen10/gen10.MMMMMMPMPM.Mary_Atherton[Mary Atherton (1636 - 1718)]



== Reference Links
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen11/gen11.MMMMMMPMPMP.Humphrey_Atherton[Book page]
* https://cfsjksas.gigalixirapp.com/person?p=p0320[Dev website]
* WeRelate TBD
* MyHeritage TBD
* Geni TBD
* WikiTree TBD

== Relations
=== Lineage #1
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen1/gen1.P.Herbert_Kirkwood_Sparrell[Herbert Kirkwood Sparrell (1899 - 1978)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen2/gen2.PM.Lavinia_Elizabeth_Strong[Lavinia Elizabeth Strong (1875 - 1941)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen3/gen3.PMM.Alice_Virginia_Edgecomb[Alice Virginia Edgecomb (1850 - 1914)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen4/gen4.PMMM.Sarah_Lavinia_Kimball[Sarah Lavinia Kimball (1830 - 1909)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen5/gen5.PMMMM.Lydia_Ann_Lester[Lydia Ann Lester (1802 - 1888)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen6/gen6.PMMMMM.Sarah_Avery[Sarah Avery (1781 - 1872)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen7/gen7.PMMMMMP.James_Avery[James Avery (1737 - 1822)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen8/gen8.PMMMMMPM.Elizabeth_Billings[Elizabeth Billings (1713 - 1791)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen9/gen9.PMMMMMPMP.William_Billings[William Billings (1660 - 1738)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen10/gen10.PMMMMMPMPM.Mary_Atherton[Mary Atherton (1636 - 1718)]

* Humphrey Atherton (1607 - 1661)

=== Lineage #2
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen1/gen1.M.Marion_F_Fisher[Marion F Fisher (1904 - 2002)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen2/gen2.MM.Ida_A_Hurlburt[Ida A Hurlburt (1874 - 1965)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen3/gen3.MMM.Martha_Avery_Edgecomb[Martha Avery Edgecomb (1855 - 1939)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen4/gen4.MMMM.Sarah_Lavinia_Kimball[Sarah Lavinia Kimball (1830 - 1909)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen5/gen5.MMMMM.Lydia_Ann_Lester[Lydia Ann Lester (1802 - 1888)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen6/gen6.MMMMMM.Sarah_Avery[Sarah Avery (1781 - 1872)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen7/gen7.MMMMMMP.James_Avery[James Avery (1737 - 1822)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen8/gen8.MMMMMMPM.Elizabeth_Billings[Elizabeth Billings (1713 - 1791)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen9/gen9.MMMMMMPMP.William_Billings[William Billings (1660 - 1738)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen10/gen10.MMMMMMPMPM.Mary_Atherton[Mary Atherton (1636 - 1718)]

* Humphrey Atherton (1607 - 1661)


== Other
emigration:  Freeman of Boston
----
2 DATE 2 MAY 1636
2 AGE About 28-29
----

event:  Major general until death
----
2 TYPE Military Service
2 DATE 1656
2 AGE About 48-49
----
 Captain - Artillery Company
----
2 TYPE Military Service
2 DATE 1650
2 AGE About 42-43
----
 (See notes)
----
2 TYPE Fact 9
----
 Assistant until his death
----
2 TYPE Fact 7
2 DATE 1654
2 AGE About 46-47
----
 Representative nine years (intermittent)
----
2 TYPE Fact 4
2 DATE 1638
2 AGE About 30-31
----
 Joined Artillery Company of Boston
----
2 TYPE Military Service
2 DATE 1636
2 AGE About 28-29
----

immigration: Arr. Boston in the ship "James"
----
2 DATE 1635
2 AGE About 27-28
----

notes: <p>He early showed a decided taste for military affairs, and soon became amember of the Ancient and Honorable Artillery Company, and was its captain from 1650 to 1658.  In 1644, he organized the first
----
2 CONC  train-band in Dorchester. Later on he commanded the Suffolk regiment with the title of Major-General, and was the chief military officer in New England.  Formany years he served as selectman and town
2 CONC  treasurer, and in 1638 and 1641, was Deputy to the General Court. <p></p> <p>Uncas, the Mohegan Sachem, after 1637 claimed vast territory in the vicinity of Norwich CT as a result of his assistance t
2 CONC o the English in the Pequot War. Major General Humphrey Atherton was sent there by the United Colonies with 40 men to protect Uncas in his person and property. ThereMantinomo, Sachem of the Narraganse
2 CONC tt Indians, was forced to sign a treaty with the United Colonies and to pay 2000 fathoms of white wampum damages and to leave hostages (children) with the United Colonies. When the damages claimed wer
2 CONC e not paid, Atherton with twenty men marched to the wigwam of Pessacus, the Narragansett Sachem, and seizing him by the hair of the head drew him from the midst of his attendants, declaring that if th
2 CONC ey should make the least resistance he would dispatch him in an instant. Therupon Pessacus was so alarmed that he paid all his damages.Atherton's demands for large sums of wampum appeared to have led 
2 CONC to the organization of the so-called "Atherton Company".  On 11 June and4 July1659, he and his "Partners" in the Atherton Company acquired from theIndian sachems large grants of land, situated west of
2 CONC  Narragansett Bay, and these grants were confirmed 14 June 1660. <p></p> <p>In 1645 the Commissioners of the United Colonies appointed a Council ofWar, which was composed of Captain Standish of Plymou
2 CONC th, Mason of Connecticut, and Leverett and Atherton of Massachusetts.</p> <p></p> <p>On 16 September 1661, Atherton was returning from a military review on Boston Common when his horse stumbled over a
2 CONC  cow and he was fatally injured.</p> <p></p> <p>Johnson gives him good character; but Hubbard excites our suspicion that everybody did not value him so highly, when he remarks that by some the manner 
2 CONC of his death was noted as a judgement.</p> <p></p>
----


== Sources
