= Anthony Collamore (1640 - 1693)

Narrative TBD


== Vital Stats


* Sex: M
* Birth: ABT 1640
* Birthplace: Northam, Devonshire, England, UK
* Death: 16 DEC 1693
* Death note: sea off North Scituate
* Age at Death: About 52-53
* Death Cause: Drowning


== Family
* Mother: Out of Scope

* Father: Out of Scope

* Child*: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen9/gen9.PPPPMMMMM.Mary_Collamore[Mary Collamore (1667 - ?)]



== Reference Links
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen10/gen10.PPPPMMMMMP.Anthony_Collamore[Book page]
* https://cfsjksas.gigalixirapp.com/person?p=p0214[Dev website]
* WeRelate TBD
* MyHeritage TBD
* Geni TBD
* WikiTree TBD

== Relations
=== Lineage #1
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen1/gen1.P.Herbert_Kirkwood_Sparrell[Herbert Kirkwood Sparrell (1899 - 1978)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen2/gen2.PP.Charles_Herbert_Sparrell[Charles Herbert Sparrell (1873 - 1961)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen3/gen3.PPP.Herbert_Kirkwood_Sparrell[Herbert Kirkwood Sparrell (1847 - 1923)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen4/gen4.PPPP.James_Newton_Sparrell[James Newton Sparrell (1825 - 1877)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen5/gen5.PPPPP.James_Newton_Sparrell[James Newton Sparrell (1798 - 1859)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen6/gen6.PPPPPP.James_Newton_Sparrell[James Newton Sparrell (1770 - 1826)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen7/gen7.PPPPPPM.Ruth_Vinal[Ruth Vinal (1746 - 1810)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen8/gen8.PPPPPPMM.Mary_Stetson[Mary Stetson (1717 - 1800)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen9/gen9.PPPPPPMMP.Anthony_Stetson[Anthony Stetson (1693 - 1747)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen10/gen10.PPPPPPMMPM.Mary_Collamore[Mary Collamore (1667 - ?)]

* Anthony Collamore (1640 - 1693)

=== Lineage #2
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen1/gen1.P.Herbert_Kirkwood_Sparrell[Herbert Kirkwood Sparrell (1899 - 1978)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen2/gen2.PP.Charles_Herbert_Sparrell[Charles Herbert Sparrell (1873 - 1961)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen3/gen3.PPP.Herbert_Kirkwood_Sparrell[Herbert Kirkwood Sparrell (1847 - 1923)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen4/gen4.PPPP.James_Newton_Sparrell[James Newton Sparrell (1825 - 1877)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen5/gen5.PPPPM.Desire_Sparrell[Desire Sparrell (1798 - 1872)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen6/gen6.PPPPMM.Martha_Farrow[Martha Farrow (1754 - ?)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen7/gen7.PPPPMMM.Jemimah_Damon[Jemimah Damon (1724 - ?)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen8/gen8.PPPPMMMM.Jemimah_Stetson[Jemimah Stetson (1695 - ?)]

* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/gen9/gen9.PPPPMMMMM.Mary_Collamore[Mary Collamore (1667 - ?)]

* Anthony Collamore (1640 - 1693)


== Other
description:  <DSCR><DESCRIPTION>&lt;DESC&gt;&lt;/DESC&gt;</DESCRIPTION></DSCR>
emigration:  Northam Devon to Scitiate
----
2 DATE 1665
2 AGE About 24-25
----

event:  Captain - Scituate Militia Company
----
2 TYPE Military Service
2 DATE 1692
2 AGE About 51-52
----
 Drowning
----
2 TYPE _DCAUSE
----
 Lieutenant, Scituate Militia
----
2 TYPE Military Service
2 DATE 1686
2 AGE About 45-46
----

notes: <p></p> <p>Peter Collamore settled at Wills Island in the marshes on the Scituate side of the North River before 1643. In 1650 he purchased a farm from Edward Foster on the adjacent mainland (The Coll
----
2 CONC amore farm site consistedof 20 acres of upland roughly bounded by  the present Route 3A on the west, the Driftway to the north and the North River marshes to the east and south together with 12 acres 
2 CONC of adjoining marsh. Being childless, Peter wrote to his brother in Northam, Devon with a request that one of his nephews come to New England to be his heir. In 1665, Anthony Collamore accepted the inv
2 CONC itation andcame to live with his uncle. Peter died in 1684 and left his estate including the sloop Mayflower  and the farm to Anthony, as promised. <p></p> <p>In 1666 Anthony Collamore married Sarah C
2 CONC hittenden and over the following 13 years, they had one son and four daughters. Anthony was active inthe Scituate militia company, rising through the ranks to Lieutenant in1686 and Captain in 1692. <p
2 CONC ></p> <p>On December 15, 1693, Anthony Collamore loaded his sloop at Hobart?s Landing  with a cargo of firewood for the Boston market. He sailed down the North river as soon as the tide started to ebb
2 CONC  in orderto take advantage of the current and to cross the bar at the old mouth without grounding. He then entered Scituate harbor  and anchored for the night. Thefollowing morning five passengers for
2 CONC  Boston boarded the sloop - two men, a woman and two "lads". The day was overcast with a raw wind from thenorth-northeast. However, the weather did not seem unduly threateningand several vessels inclu
2 CONC ding Collamore?s sloop put to sea as the tidestarted to ebb. <p></p> <p>Collamore's vessel was noted by several observers as it sailed north along the Scituate coast over the next hour. During that ti
2 CONC me, a storm was rapidly developing and Collamore's sloop finally disappeared from view in a blizzard of wind-driven snow. Before dark of that same day, billets of cordwood and wreckage from a vessel b
2 CONC egan coming ashore on NorthScituate beach. On the following day, the body of Ephraim Turner, aged26, came ashore on the beach. Fourteen days later, the body of AnthonyCollamore came ashore so badly ba
2 CONC ttered that identification could onlybe made from his clothing. Collamore?s body was escorted to the old church on Meetinghouse Lane by the militia company under arms and he was buriedbeside the churc
2 CONC h. No other bodies were ever recovered. <p></p> <p>From the pattern of the wreckage and cargo on North Scituate beach and the rapidity with which it came ashore, it was apparent that the sloop had bee
2 CONC n driven on a ledge just offshore. That ledge has been identifiedon marine charts ever since as "Collamore's Ledge". <p></p> <p>A monument which includes the original slate headstone was later erected
2 CONC  in the Old Meeting House Cemetary by Anthony's descendants.</p> <p></p> <p>Ancestor of Presidents William Henry Harrison and Benjamin Harrison.</p>
----

residence: 
----
2 WWW %3A+http%3A%2F%2Fwww.werelate.org%2Fwiki%2FPerson%3AAnthony_Collamore_%281%29:
----

title: Captain

== Sources
