= Albert Amory Fisk Fisher

Born in Cohasset, Massachusetts on October 25, 1854. Died in Hampton, Connecticut on December 15, 1915. Listed as the son of link:https://github.com/sparrell/CfsJksAs/blob/main/priv/static/adoc/V2_C5_G4/gen4.MPMP.Albert_Fisher.adoc[Albert Fisher] and link:https://github.com/sparrell/CfsJksAs/blob/main/priv/static/adoc/V2_C5_G4/gen4.MPMM.Arvilla_Gray.adoc[Arvilla Gray]. Husband to link:https://github.com/sparrell/CfsJksAs/blob/main/priv/static/adoc/V2_C5_G2/gen2.MM.Ida_A_Hurlburt.adoc[Ida A Hurlburt]. Father to link:https://github.com/sparrell/CfsJksAs/blob/main/priv/static/adoc/V2_C5_G1/gen1.M.Marion_F_Fisher.adoc[Marion F. Fisher].


Certified Genealogist Polly FitzGerald Kimmitt has revealed the possibility that Albert AF Fisher's "sister" was actually his birth mother. Though he was raised as a son in the household of Albert Fisher (1812-1887) and Arvilla Gray (1808-1888), the circumstances and timing of his birth raise questions.
Given the relative stability of his parents, it is unusual that Albert AF Fisher’s birth record lists Albert Fisher as his father, but the field for mother is left blank. It would also be remarkable if Arvilla Gray – nominally Albert AF Fisher’s mother – had given birth to him in 1854. She would have been forty-six at the time. 
In accounting for these discontinuities, one intriguing possibility lurks in the family tree. At the time of his birth, Albert AF Fisher’s “sister,” Frances Fisher, was eighteen or nineteen. No record for her birth exists. Following a gap in historical records, Frances reappears to posterity in 1856 when she married Henry H. Barr in Cincinnati, Ohio. Frances had her first child in wedlock in 1857. The timing relative to the birth of her "brother", Albert AF Fisher, is curious.
There is reasonable cause to suspect that Frances might have been Albert AF Fisher’s actual mother and that her parents, Albert and Arvilla Fisher, raised the younger Albert as their own.     
