= Albert Amory Fisk Fisher

Some material facts of Albert Amory Fisk Fisher’s life are indisputable. He was born October 25, 1854, in Cohasset, Massachusetts. He died on December 15, 1915, in Hampton, Massachusetts. In 1904, Albert Amory Fisk Fisher and his second wife (and former secretary), Ida, welcomed their son Marion Fisher into the world. 
Thorough genealogy work has revealed that the once settled matter of Albert Amory Fisk Fisher’s parentage is ambiguous. Though he was raised as a son in the household of Albert Fisher (1812-1887) and Arvilla Gray (1808-1888), the circumstances and timing of his birth raise questions.
Given the relative stability of his parents, it is unusual that Albert AF Fisher’s birth record lists Albert Fisher as his father, but the field for mother is left blank. It would also be remarkable if Arvilla Gray – nominally Albert AF Fisher’s mother – had given birth to him in 1854. She would have been forty-six at the time. 
In accounting for these discontinuities, one intriguing possibility lurks in the family tree. At the time of his birth, Albert AF Fisher’s “sister,” Frances Fisher, was eighteen or nineteen. No record for her birth exists. In 1856, Frances decamped from Massachusetts and moved to Cincinnati, Ohio with her new husband, Henry H Barr. They had their first child in 1857. The timing relative to the birth of her nominal brother is curious.
There is reasonable cause to suspect that Frances might have been Albert AF Fisher’s actual mother and that her parents, Albert and Arvilla Fisher, raised the younger Albert as their own.     
