= Arvilla Gray (1808 - 1888)= Arvilla Gray Fisher

The cultural mores and biological realities of 19th century American life call to question the viability of previously accepted genealogical arrangements. Arvilla Gray Fisher (1808-1888) has historically occupied the role of mother to both Frances Fisher (b. 1834) and Albert AF Fisher (b. 1854). It would be extraordinary if Arvilla had, in fact, given birth to these two children nineteen years apart. At age forty-six, her supposed delivery of Albert AF Fisher would have been uncommon for the age. 
Enduring questions about the lack of birth mother and parent place of birth reporting on Albert AF Fisher’s birth record dovetail with Frances Fisher’s subsequent obscurity in the historical record and reemergence two years later in Ohio. In the 1880s, Arvilla listed Albert AF Fisher as executor of her will, indicating deep familial ties. 
Whatever the nature of their relationship, pioneering work by genealogist Polly FitzGerald Kimmitt raises enough questions to incorporate Arvilla Gray Fisher and her husband Albert in the role of grandparents for Albert AF Fisher.

== Vital Stats


* Sex: F
* Birth: 4 JAN 1808
* Birthplace: Paris, Oxford, Maine, USA
* Death: 14 JUL 1888
* Deathplace: Dedham, Norfolk, Massachusetts, USA
* Buried: 

* DATE 17 JUL 1888

* PLAC Groveland Cemetery, Dedham, Norfolk, Massachusetts, USA
* Age at Death: 80


== Family
* Mother: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G5/gen5.MPMMM.Rhoda_Andrews.adoc[Rhoda Andrews (1775 - 1841)]

* Father: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G5/gen5.MPMMP.John_Gray.adoc[John Gray (1763 - 1841)]

* Child*: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.MPM.Frances_A_Fisher.adoc[Frances A Fisher (1835 - ?)]


== Reference Links
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G4/gen4.MPMM.Arvilla_Gray.adoc[Book Link]
https://cfsjksas.gigalixirapp.com/person?p=p0189http://localhost:4000/person?p=p0189https://cfsjksas.gigalixirapp.com/adoc?p=p0189http://localhost:4000/adoc?p=p0189* https://www.geni.com/people/Arvilla-Gray/6000000219179990052[Geni]
* https://www.myheritage.com/profile-OYYV6NML2DHJUFEXHD45V4W32Y6KPTI-23000423/arvilla-gray-fisher[MyHeritage]
* https://www.werelate.org/wiki/Person:Arvilla_Gray_%281%29[WeRelate]
* WikiTree TBD

== Relations
=== Lineage #1
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G1/gen1.M.Marion_F_Fisher.adoc[Marion F Fisher (1904 - 2002)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G2/gen2.MP.Albert_Amory_Fisk_Fisher.adoc[Albert Amory Fisk Fisher (1854 - 1915)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.MPM.Frances_A_Fisher.adoc[Frances A Fisher (1835 - ?)]
* gen4.MPMM.Arvilla_Gray_(1808 - 1888)


== Other
census: 

* DATE 1880

* PLAC Dedham, Norfolk, Massachusetts, USA

* AGE 71-72
occupation: Keeps House

== Sources

