= Albert Fisher (1812 - 1887)= Albert Fisher

Born in 1812, Albert Fisher was a railroad engineer whose work in Maine potentially connected him with his wife, Arvilla Gray (1808-1888). Since their deaths a year apart in the 1880s, the Fishers have occupied a static role in the family tree, with both Frances Fisher (b. 1835) and Albert AF Fisher (b. 1854) integrated as presumed children of the couple.
That logic has changed recently as emerging evidence suggests that Frances Fisher was the only child of Albert and Arvilla Fisher and that Albert AF Fisher, who was raised as her brother, was, in fact, her son. 
This accounts for the lack of a birth mother and parent birthplace information on Albert AF Fisher’s 1854 birth record as well as the nineteen-year gap between Frances and Albert AF’s births. Biologically, Frances was the more likely mother of Albert AF Fisher. Her mother (and Albert AF’s historically recognized mother), Arvilla Gray Fisher would have been forty-six at the time of young Albert’s birth.
Though not confirmed, the likelihood of this scenario is weighty enough to merit a reconfiguration in the family tree so that Albert Fisher is recognized as Albert AF Fisher’s grandfather and not his father. 

== Vital Stats


* Sex: M
* Birth: 27 JUN 1812
* Birthplace: Bolton, Worcester, Massachusetts, USA
* Death: 8 JUN 1887
* Deathplace: Dedham, Norfolk, Massachusetts, USA
* Buried: 

* DATE 10 JUN 1887

* PLAC Groveland Cemetery, Dedham, Norfolk, Massachusetts, USA
* Age at Death: 74


== Family
* Mother: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G5/gen5.MPMPM.Ann_Pierce.adoc[Ann Pierce (? - ?)]

* Father: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G5/gen5.MPMPP.Jacob_Fisher.adoc[Jacob Fisher (1776 - 1820)]

* Child*: https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.MPM.Frances_A_Fisher.adoc[Frances A Fisher (1835 - ?)]


== Reference Links
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G4/gen4.MPMP.Albert_Fisher.adoc[Book Link]
https://cfsjksas.gigalixirapp.com/person?p=p0188http://localhost:4000/person?p=p0188https://cfsjksas.gigalixirapp.com/adoc?p=p0188http://localhost:4000/adoc?p=p0188* https://www.geni.com/people/Albert-Fisher/6000000219179990038[Geni]
* https://www.myheritage.com/profile-OYYV6NML2DHJUFEXHD45V4W32Y6KPTI-23000422/albert-fisher[MyHeritage]
* https://www.werelate.org/wiki/Person:Albert_Fisher_%2812%29[WeRelate]
* WikiTree TBD

== Relations
=== Lineage #1
* https://github.com/spoarrell/cfs_ancestors/tree/main/Vol_02_Ships/V2_C1_Principals/0_intro_principals.adoc[Charles, James, Ann Sparrell]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G1/gen1.M.Marion_F_Fisher.adoc[Marion F Fisher (1904 - 2002)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G2/gen2.MP.Albert_Amory_Fisk_Fisher.adoc[Albert Amory Fisk Fisher (1854 - 1915)]
* https://github.com/sparrell/cfs_ancestors/blob/main/Vol_02_Ships/V2_C5_Ancestors/V2_C5_G3/gen3.MPM.Frances_A_Fisher.adoc[Frances A Fisher (1835 - ?)]
* gen4.MPMP.Albert_Fisher_(1812 - 1887)


== Other
census: 

* DATE 1880

* PLAC Dedham, Norfolk, Massachusetts, USA

* AGE 67-68
event:  See Notes

* TYPE Misc
notes: 1854 Birth record of Albert A. F. Fisher lists father's occupation as Engineer and residence as Cohasset MA. 1880 Federal Census Lists Albert(69) as a farmer in Dedham MA. Living at the same location is his wife Arvilla (70), his son Albert F.(25) , his Daughter-in-law, Anna W.(24) and a granddaughter Adelle(2). Buried Groveland Cemetary, Dedham, MA
occupation: Farmer

== Sources

